#
###################################
# Site wide configuration
####################################
#
title: jcp  
email: janicecpoon@gmail.com 
description: my travel log
url: https://janicep.github.io # the base hostname & protocol for your site
keywords: ["Travel", "Photojournal", "Blog"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          '+0700' 
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: jcp
  avatar: jp-avatar.png
  job: "Wandering post-grad"
  bio: "a daily(-ish) photo log of my time abroad"
  email: janicecpoon@gmail.com  
  disqus-shortname: 
  twitter:  #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin:  #username
  xing: #username
  instagram: janipoon #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
